name = "DEtection"
uuid = "6e6122cf-0651-4e8d-ba44-faf83b947c7a"
authors = ["Josh North <jsnowynorth@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.7.2"
DataFrames = "1.3.2"
DataFramesMeta = "0.10.0"